### ISSUE TITLE
[Feat] add title & subtitle to accidents_heat_map widget

### ISSUE THREAD

**Issue by MichalOren** [data-for-change/anyway-newsflash-infographics#1014]
**description**
This widget missing title & subtitle

**Expected display**
![image](https://github.com/data-for-change/anyway-newsflash-infographics/assets/61007501/51a85b71-39a5-4dd9-9de7-bc9016213d30)

**Comment by MichalOren** [comment]
מגניב , כל הכבוד

**Comment by shaked-hayek** [comment]
Fixed in https://github.com/data-for-change/anyway-newsflash-infographics/pull/1015
