### ISSUE TITLE
[Bug] Infographics are not displayed in newsflash

### ISSUE THREAD

**Issue by atalyaalon** [data-for-change/anyway-newsflash-infographics#1019]
**Describe the bug**
Infographics are not displayed in newsflash even though api data exists

https://media.anyway.co.il/newsflash/181016

**Screenshots**

![Screenshot 2024-01-03 at 17 28 07](https://github.com/data-for-change/anyway-newsflash-infographics/assets/20992625/e1a48761-f1fc-4619-9f36-9713b6b46253)

@EyalIlan can you take a look?

**Comment by MichalOren** [comment]
אין בגן יבנה רחוב בשם המשוררת רחל. שם הרחוב בגן יבנה הוא רחל המשוררת (ולא המשוררת רחל).
מיקום התאונה הוא בישוב גן יבנה ברחוב רחל המשוררת.
ביבנה קיים רחוב בשם רחל המשוררת. נראה שחל בלבול במבזק עצמו.
לא באג שלנו
