### ISSUE TITLE
[Bug]: Need to adjust title when road name is very long

### ISSUE THREAD

**Issue by MichalOren** [data-for-change/anyway-newsflash-infographics#1029]
**Bug Description**
When the road segment name is very long, the title does not look good
injured_count_by_severity & accident_count_by_severity
![image](https://github.com/data-for-change/anyway-newsflash-infographics/assets/61007501/677f4d53-6636-4501-b2b2-ce26f7db9bfd)

**To Reproduce**
https://anyway-infographics-staging.web.app/newsflash/182869

**Expected behavior**
For injured_count_by_severity & accident_count_by_severity - adjust infografic position 
![image](https://github.com/data-for-change/anyway-newsflash-infographics/assets/61007501/e0b64c00-b00e-4666-8f79-bb11591df7c6)

For most_severe_accidents_table widget - check if reducing line space is an option

**Comment by atalyaalon** [comment]
@byakter is this done?
