### ISSUE TITLE
[Bug]: Numbers on stacked bar are misleading

### ISSUE THREAD

**Issue by MichalOren** [data-for-change/anyway-newsflash-infographics#1050]
**The bug**
Relevant widgets are:
-injured_count_by_accident_year
-accident_count_by_accident_year

The problem is: for example, in the casualty graph, you can see the numbers of lightly injured and usually you don't see the numbers of those seriously injured or killed. All data is displayed only by hovering with the mouse. One can mistakenly think that the number of lightly wounded is the total number of casualties

![image](https://github.com/data-for-change/anyway-newsflash-infographics/assets/61007501/3641d5fd-5eb0-4ecb-8fe6-9b68095ceaee)

**To Reproduce**
https://anyway-infographics-staging.web.app/newsflash/185166

**New expected behavior**
Display graph **grid** in the background

**Screenshots**
![image](https://github.com/data-for-change/anyway-newsflash-infographics/assets/61007501/9b99fde3-68b5-4030-92d7-dc6c56752dec)

https://recharts.org/en-US/examples/StackedBarChart

**Additional context**
hopefully we want to keep current numbers. not sure U are welcome to consult product team

**Comment by atalyaalon** [comment]
@SejoB reopening, see discussion in attached pr

**Comment by atalyaalon** [comment]
@SejoB Is there an option to add horizontal grid (not dashed but full line) just like this image?

![image](https://github.com/data-for-change/anyway-newsflash-infographics/assets/61007501/e93ad84a-2790-4ff0-a3f3-74a9aaf8f345)

**Comment by SejoB** [comment]
@atalyaalon 
Just added a horizontal tick lines. PR is opened.
If need some styling on the lines, let me know
![image](https://github.com/data-for-change/anyway-newsflash-infographics/assets/39242962/eedd1c70-3235-4ce1-8961-c4a1f62d6b32)
