### ISSUE TITLE
[Bug] N12 view - הכל text is in white rather than black

### ISSUE THREAD

**Issue by atalyaalon** [data-for-change/anyway-newsflash-infographics#1072]
**Describe the bug**
N12 view - text of "הכל" is in white, should be black

<img width="333" alt="Screenshot 2024-03-06 at 20 44 57" src="https://github.com/data-for-change/anyway-newsflash-infographics/assets/20992625/d98f8e49-8c61-4fc1-b2d7-cd5d4309f007">

**Comment by MichalOren** [comment]
Hi 
that happen also in "חיפוש" after selecting road segment
Kindly check the text  is in white and need to be Black
![image](https://github.com/data-for-change/anyway-newsflash-infographics/assets/61007501/7fbb11e1-83a4-4a56-8eaa-9a74a30df8b0)

**Comment by MichalOren** [comment]
Additonal case: kindly check the text is in white and need to be Black
![image](https://github.com/data-for-change/anyway-newsflash-infographics/assets/61007501/77755a0b-6351-4e58-a1b0-e3c59de22035)

**Comment by MichalOren** [comment]
additional issue of text not visible
![image](https://github.com/data-for-change/anyway-newsflash-infographics/assets/61007501/7bf3b64f-9004-43a6-bab9-3ad83b762294)

**Comment by atalyaalon** [comment]
@shaked-hayek I reopened since @MichalOren added additional changes

**Comment by atalyaalon** [comment]
@shaked-hayek 
one more "white on white"

Text in the bottom

<img width="775" alt="Screenshot 2024-04-24 at 21 42 51" src="https://github.com/data-for-change/anyway-newsflash-infographics/assets/20992625/d3e48372-d707-4944-8090-78ecd0b4e754">
