### ISSUE TITLE
[Bug]: N12 location verification - The window looks cut and the text is partial

### ISSUE THREAD

**Issue by MichalOren** [data-for-change/anyway-newsflash-infographics#1081]
**Bug Description**
1. In the window that opens, the buttons below are partially displayed
2. The text above appears in white and is therefore not displayed

**To Reproduce**
![image](https://github.com/data-for-change/anyway-newsflash-infographics/assets/61007501/fd22842e-79f5-4fd0-87e0-c00ee2d6b9d9)

**Comment by shaked-hayek** [comment]
We want to add scroll bars - in the right side for up & down, and in the bottom for left & right.
Should be displayed only if the screen is larger then showed.
Then it will be okay for every screen size. Probably can use this: https://www.npmjs.com/package/react-scrollbars-custom

**Comment by atalyaalon** [comment]
Thanks @shaked-hayek 
@byakter can you take this one?

**Comment by shaked-hayek** [comment]
@atalyaalon this was fixed and can be closed, right?

**Comment by atalyaalon** [comment]
@shaked-hayek yes it's fixed.
Closing this one
