### ISSUE TITLE
[Feat] Create an infographic to present amount of injured by age group

### ISSUE THREAD

**Issue by galraij** [data-for-change/anyway-newsflash-infographics#603]
<img width="896" alt="כרטיסיות_חדשות_לעיצוב_-_סדר_עדיפויות_pdf" src="https://user-images.githubusercontent.com/3368312/109392091-dd163080-7922-11eb-8ee5-0a9e2049d9c6.png">

The age categories should be:

0-4
5-14
15-19
20-24
25-44
45-64
65+

**Comment by Mr-DannyDin** [comment]
![ANYWAY-slides](https://user-images.githubusercontent.com/79767188/109412663-f6b28900-79b1-11eb-91cf-924b54d2008c.jpg)
Hey guys! Good morning.
Is there a reason why we communicate in english?
Regardless, here's the design we made for this slide, however I believe some of the data is missing: the amount of injured in each age group. Otherwise the lengths  of the bars seem a bit arbitrary. Plus I think it's important to know the quantities of the people injured.
What do you think?

**Comment by galraij** [comment]
@Mr-DannyDin yes you are right about the quantities and it's great how you did it. 

While it's good, I would suggest if possible to include some icons of different age groups as we really want the info graphics to be different from one another and emphasize when young and elderly are being injured. So I'm not saying each age group should get an icon but maybe 2 or 3 of them can have an icon of baby and old man etc...

About the English use - Ideally one day we will be an international platform and this is the standard of communication here. Also- I believe to developers don't like switching languages when they code and look on GitHub. You can use whatever is comfortable for you. I got used to it :0

**Comment by yuvalbl** [comment]
design is finished
still need to know what happens when we have more/less bars (responsive / keep bar width?)

**Comment by yuvalbl** [comment]
Seems like when there are less bars - they take more space. Question remains

1. what is the minimum number of bars? will the server enforce it?
2. here the value is part of the bar, on the image above - it is in the gray box. which is correct?

![wide-bars-solution](https://user-images.githubusercontent.com/11487010/147384135-458bd1b4-2a18-4dcb-a684-e9b6285b2573.jpg)

**Comment by yuvalbl** [comment]
Waiting for product response for this proposal
Also - what should we do when the value is very low (like 1)? should we put the numbers above the bars?
![image](https://user-images.githubusercontent.com/11487010/148262908-9107e196-0b16-4746-ab5c-e15b35cd1fbf.png)

**Comment by MichalOren** [comment]
HI here are the designs for killed_and_injured_count_per_age_group.
One widget that counts injured all severities together (including light injured) - Simple Bar Chart API structure.
I have created 1 wireframe for urban zone and 1 for interurban zone.
Relevant API from BE is comming soon.
![Age_groups_Urban](https://user-images.githubusercontent.com/61007501/149394894-3d604280-0f0c-4a02-90af-9570e6da5293.jpeg)
![Age_groups_InterUrban](https://user-images.githubusercontent.com/61007501/149394897-61b44266-5946-4db6-9d03-dabe678531f3.jpeg)

**Comment by MichalOren** [comment]
**API structure(widget date provided by BE team)**

 "name": "killed_and_injured_count_per_age_group",
            "data": {
                "items": [
                    {
                        "label_key": "00-04",
                        "value": 18
                    },
                    {
                        "label_key": "05-14",
                        "value": 29
                    },
                    {
                        "label_key": "15-19",
                        "value": 15
                    },
                    {
                        "label_key": "20-24",
                        "value": 52
                    },
                    {
                        "label_key": "25-44",
                        "value": 241
                    },
                    {
                        "label_key": "45-64",
                        "value": 107
                    },
                    {
                        "label_key": "unknown",
                        "value": 3
                    },
                    {
                        "label_key": "65+",
                        "value": 31
                    }
                ],
                "text": {
                    "title": "נפגעים לפי קבוצת גיל",
                    "subtitle": "במקטע מחלף רמלה דרום - צומת גינתון"
                }
            },
            "meta": {
                "rank": 14,
                "information": "Project-Id-Version: PROJECT VERSION\nReport-Msgid-Bugs-To: EMAIL@ADDRESS\nPOT-Creation-Date: 2022-01-08 14:56+0200\nPO-Revision-Date: 2020-10-16 15:42+0000\nLast-Translator: FULL NAME <EMAIL@ADDRESS>\nLanguage: he\nLanguage-Team: he <LL@li.org>\nPlural-Forms: nplurals=2; plural=(n != 1)\nMIME-Version: 1.0\nContent-Type: text/plain; charset=utf-8\nContent-Transfer-Encoding: 8bit\nGenerated-By: Babel 2.9.1\n"
            }

**Comment by MichalOren** [comment]
**Full API example with news flash ID**
https://www.anyway.co.il/api/infographics-data?lang=he&news_flash_id=100919&years_ago=5

**Comment by MichalOren** [comment]
},
"meta": {
        "rank": 14,
        "information": "כמות הנפגעים : הרוגים, פצועים קשה וקל - במקטע בפרק הזמן הנבחר"
 }
