### ISSUE TITLE
[Feat] Add Design to injured_count_by_accident_year

### ISSUE THREAD

**Issue by atalyaalon** [data-for-change/anyway-newsflash-infographics#647]
**Is your feature request related to a problem? Please describe.**
API exists. Please add design.
Please use generic Bar Chart - [See design here](https://github.com/hasadna/anyway-newsflash-infographics/issues/601) (use Red color only - since it's a regular bar chart, not stacked)

UPDATE - BLOCKED
Problematic data may cause the widget to be messy

Solution:
backend should send the widget with different variants 
(total, only fatal and severe, all 3 options, etc.)
Waiting for product team
![image](https://user-images.githubusercontent.com/11487010/147887974-ac4d0239-0617-42b0-8a5d-b362d43921e3.png)

**Comment by grandcohen** [comment]
@atalyaalon What's the story we want to tell behind this chart? I'm not sure I understand what injured_count_by_accident_year mean. Do we have an early mock or can you elaborate what's this about?

**Comment by atalyaalon** [comment]
@grandcohen A total count of injured/killed per year - no deep meaning to it, just an informative graph, with one bar each year  (no categories, just a sum of all of them together).
@galraij anything to add on this one?

**Comment by grandcohen** [comment]
@atalyaalon @yuvalbl 
here's the final design for the generic bar chart. we should use that:
https://drive.google.com/file/d/17ne72PQBUtx9GwGTE13IsZNdgVjC6geY/view?usp=sharing

**Comment by atalyaalon** [comment]
@grandcohen amazing
API is ready as well
Example:
```
        {
            "name": "injured_count_by_accident_year",
            "data": {
                "items": {
                    "1": {
                        "2014": 1,
                        "2015": 1,
                        "2016": 0,
                        "2017": 0,
                        "2018": 0,
                        "2019": 0,
                        "2020": 0,
                        "2021": 0
                    },
                    "2": {
                        "2016": 1,
                        "2017": 2,
                        "2019": 1,
                        "2014": 0,
                        "2015": 0,
                        "2018": 0,
                        "2020": 0,
                        "2021": 0
                    },
                    "3": {
                        "2014": 42,
                        "2015": 31,
                        "2016": 15,
                        "2017": 42,
                        "2018": 54,
                        "2019": 31,
                        "2020": 46,
                        "2021": 9
                    }
                },
                "text": {
                    "labels": {
                        "1": {
                            "name": "killed",
                            "localized_name": "הרוג/ה"
                        },
                        "2": {
                            "name": "severe injured",
                            "localized_name": "פצוע/ה קשה"
                        },
                        "3": {
                            "name": "light injured",
                            "localized_name": "פצוע/ה קל"
                        }
                    },
                    "title": "מספר נפגעים לפי שנה, מחולקים לפי חומרה, במקטע צומת טבריה - צומת כפר נחום"
                }
            },
            "meta": {
                "rank": 9,
                "information": "מספר הרוגים, פצועים קשה וקל, לפי שנה במקטע, מחולק לפי חומרת הפגיעה, בפרק הזמן הנבחר."
            }
        }
 ```

@MichalOren FYI

**Comment by atalyaalon** [comment]
@MichalOren regarding years - Yes - param from frontend changes the years
Regarding the title, sounds good! Can you open an issue for milestone V0.9.0?

**Comment by yuvalbl** [comment]
Waiting for product review
After product work is done - backend will send couple of variants for this widget

**Comment by liron93** [comment]
1. The order should be (from top to bottom): Minor-> Severe -> dead
>
![149149917-7f666cd5-ab90-4425-9860-fbc4566a6244-2](https://user-images.githubusercontent.com/96621915/153255993-88318043-335c-4c4d-9737-77ab6616a05e.png)
 Waiting for a product review @danielsh28 
> After product work is done - backend will send a couple of variants for this widget @atalyaalon

**Comment by atalyaalon** [comment]
@liron93 the order is done in the BE, @BarVolunteering has been working on this

**Comment by BarVolunteering** [comment]
It's on staging, there is a PR to PROD ([#2106](https://github.com/hasadna/anyway/pull/2106))

**Comment by yuvalbl** [comment]
Is it still blocked?
Seems close to completion

**Comment by atalyaalon** [comment]
@yuvalbl not blocked, can you proceed with this one?

**Comment by MichalOren** [comment]
Hi  injured_count_by_accident_year widget **face lift**
- use  "title": מספר נפגעים לפי שנה, לפי חומרה “subtitle": צומת דימונה - צומת בית אשל
please don't concatenate them but keep etch one in a different row
- legend: main change is in the legend location below or above the graph. preferably below. 
- kindly keep same font
- Add a space in the legend between the point and the text(not madatory)

Option 1 
![image](https://github.com/data-for-change/anyway-newsflash-infographics/assets/61007501/429e0eab-5f0d-4c4e-849b-048b8d7bdceb)


Option 2
![image](https://github.com/data-for-change/anyway-newsflash-infographics/assets/61007501/1fbcd5b2-e93f-47cd-ba18-99fcd4ac5d79)

**Comment by shaked-hayek** [comment]
done
