### ISSUE TITLE
Map - Create Clusters in FE for near or exact-location accidents

### ISSUE THREAD

**Issue by atalyaalon** [data-for-change/anyway-newsflash-infographics#648]
Update: let's start implementing this, while keeping in mind icons should be replaced by ours
https://leaflet.github.io/Leaflet.markercluster/example/marker-clustering-realworld.388.html

Widget Name: most_severe_accidents

Currently, accidents can overlap if they are near each other or have the same GPS location (as shown in the Screen shot). It's impossible to know how many accidents are overlapping and move their labels so at least the labels are not overlapping (simply because you can't select the accident that is not on top).
![ANYWAY](https://user-images.githubusercontent.com/3368312/109390477-8dcc0200-791a-11eb-9a21-86c95ae15606.png)

What should be done:
1. Design- WIP - https://github.com/hasadna/anyway-newsflash-infographics/issues/600
![ANYWAY_-_Making_a_difference_in_any_way](https://user-images.githubusercontent.com/3368312/109390726-fc5d8f80-791b-11eb-9d37-553da0c1576c.png)
![ANYWAY_-_Making_a_difference_in_any_way](https://user-images.githubusercontent.com/3368312/109390732-07182480-791c-11eb-9534-5cd41adc44ae.png)
![ANYWAY_-_Making_a_difference_in_any_way](https://user-images.githubusercontent.com/3368312/109390746-10a18c80-791c-11eb-90e0-ebf6ab9a0f89.png)
2. FE - create an automatic clustering that is changing according to the map's zoom. (like in the anyway.co.il map).
3. FE - Consolidate all dates into one label presented next to the cluster icon, or, if using the "flower" version (in which many icons are tied with lines to one point on the map) have the dates presented next to each icon in a readable way.

**Comment by yuvalbl** [comment]
How about this?
https://leaflet.github.io/Leaflet.markercluster/example/marker-clustering-realworld.388.html

**Comment by yuvalbl** [comment]
![image](https://user-images.githubusercontent.com/11487010/117990811-300a5c00-b346-11eb-9277-16a5d1b49cd9.png)

**Comment by daniel-ilan** [comment]
This is an initial implementation of the clustering - it still needs refactoring but it demonstrates the usage.
We can use it the same way as in anyway.co.il.
We will still have the ability to select the label's position next to the icon.
I will be waiting for instructions on how to continue with this.


Close cluster:
![image](https://user-images.githubusercontent.com/37712687/118109676-2c301580-b3ea-11eb-8abe-95a4c3f31b24.png)

Open cluster:
![image](https://user-images.githubusercontent.com/37712687/118108309-829c5480-b3e8-11eb-8424-b2c06c168451.png)
