### ISSUE TITLE
[Feat] Add design and connect API for the new injured_count_per_age_group widget

### ISSUE THREAD

**Issue by atalyaalon** [data-for-change/anyway-newsflash-infographics#827]
1. Design is here:
Note that the title should come from the BE only (the title in the design is not accurate)
![current design](https://user-images.githubusercontent.com/79767188/109651583-63bb4f80-7b67-11eb-913b-e2f8f35013ab.jpg)

[All designs in drive](https://drive.google.com/drive/u/0/folders/182CSCMpusZmeQTFIVu-JLUrdNQeyeuJ9)

2. Final API not ready - please discuss with the BE team to finalize the structure - see [this issue](https://github.com/hasadna/anyway/issues/1969)
A structure of generic bar graph can be used.

**Comment by BarVolunteering** [comment]
The widges names will be:
killed_and_injured_count_per_age_group 
killed_and_injured_count_per_age_group_stacked

**Comment by atalyaalon** [comment]
@danielsh28 we want to prioritize this.
Liron can create wireframes.

**Comment by danielsh28** [comment]
@MichalOren does the design can be as the already existing bar chart? or are we required to implement this new one ( when the values are in this grey clouds?

**Comment by MichalOren** [comment]
Hi Daniel and Itai
The design can be be as the already existing bar chart 
Is the **Total** value will be display inside the bar?

**Comment by ItaiOz** [comment]
Hi @MichalOren, 
I think there is an error with data coming from API since there is an 'unknown' group age to appear.

![Screenshot 2022-07-11 131225](https://user-images.githubusercontent.com/72853162/178242082-f9467f36-f5dc-4e12-9cce-b62252d59774.png)

**Comment by danielsh28** [comment]
@ziv17 @atalyaalon  @MichalOren  what do you want to do with the unknown group?

**Comment by MichalOren** [comment]
Hi all 
I think we should remove the 'unknown group' from the bar graph. 
But since it should match other widgets (total of injured in other widgets in the road section) we should add a notification. Under the graph add * **<14>** injured, age unknown 
what do you think?

**Comment by ziv17** [comment]
I agree

**Comment by danielsh28** [comment]
@zive can you remove the unknown group ?

**Comment by ziv17** [comment]
@danielsh28 yes we can, but shouldn't we display the number of injured that we do not have their age? probably not as a bar, but somewhere else, like @MichalOren suggested?

**Comment by danielsh28** [comment]
@MichalOren for your approval, 
 can we continue with this current design and maybe we can add the 'cloud' element later?

<img width="588" alt="Screen Shot 2022-08-27 at 21 59 11" src="https://user-images.githubusercontent.com/28825057/187044747-3d926c51-2822-468a-9dda-82ef35b50f18.png">

**Comment by MichalOren** [comment]
Hi FE Team 
**This is great progress**. 👍 our first sipmle graph bar (:
It's important to add this widget to our Staging Environment for our up coming meeting with OrYarok. 

Therefor, we can proceed and handle "unknown" group later in time. 
The 'cloud' element is not a must in 'simple bar graph' (It is mandatory in stacked graph).

2 notes before implementation -  see in the following image
a. Road number is a mast (mark in green dash line) 
b. Title align to center (mark in blue dash line)
![image](https://user-images.githubusercontent.com/61007501/187089431-c4378a34-ee4c-4db3-962c-7a72ee2fc729.png)

**Comment by atalyaalon** [comment]
Unknown issue solved
