### ISSUE TITLE
[Feat]: Title bold and centered

### ISSUE THREAD

**Issue by MichalOren** [data-for-change/anyway-newsflash-infographics#954]
**General description**
We recently rearrange JSON structure, each widget now have a title and subtitle

**Requested change**
Go over widgets titles and make it bold and centered 

**visualization**
![image](https://user-images.githubusercontent.com/61007501/224475650-421b2d41-c72f-41f5-b6b4-ee5538a62e28.png)

**Comment by MichalOren** [comment]
@danielsh28 
kindly assign to relevant person.
can you give a permission to assign ?

**Comment by shaked-hayek** [comment]
fixed and merged
