### ISSUE TITLE
[Feat]: location qualification UI-after adding critical newsflash icon

### ISSUE THREAD

**Issue by MichalOren** [data-for-change/anyway-newsflash-infographics#956]
**General description**
As part of 'Newsflash location qualification' improvement, we are creating new user interface.
An interface that allows users to change and specify the location of the accident

full decription of the change in issue [2218](https://github.com/data-for-change/anyway/issues/2218)

**Requested change**
Stage A with Or Yarok, is to reflect in current UI the ability to update a location. in this stage no need to build the infrastructure and the functionality behind it.

**visualization**

![image](https://user-images.githubusercontent.com/61007501/225127396-e68de96d-aa05-4ffc-8827-995ed6cb710e.png)

![image](https://user-images.githubusercontent.com/61007501/225126577-18776b85-ba4a-4fea-934c-0a406bb7c3e3.png)

**Comment by MichalOren** [comment]
@danielsh28

**Comment by shaked-hayek** [comment]
@MichalOren seems to me this is done, I'm closing the issue
