### ISSUE TITLE
[Feat] Add transcrption to 4 widgests

### ISSUE THREAD

**Issue by MichalOren** [data-for-change/anyway-newsflash-infographics#957]
**General description**
New JSON tag named **transcription** was added. 
It hold the generated text from dedicated template code for etch widget.
Currently only 4 widgets will have transcription content:
1. accident_count_by_severity
2. injured_count_by_severity
3. head_on_collisions_comparison_percentage
4. most_severe_accidents_table

**Requested change**
a. Add T icon for relevant widgets 
b. When user will click on T icon it will open new window 
c. The New window display 'transcription tag' text content
d. The new window will have a copy button enable the user export the text (see image) 

![image](https://user-images.githubusercontent.com/61007501/226199249-9d8ab6cf-1e48-4c3d-b339-b9a83b8e4089.png)

![image](https://user-images.githubusercontent.com/61007501/226199321-4f470da8-0162-4e1e-b77e-18e9313afa0a.png)

**Additional context**
This text will be also used a part of full article

**Comment by EyalIlan** [comment]
hey question about the task when you click on the T icon the individual  widget should switch to the box with the text or open a full screen with the box text like when you click on the expend icon with the arrows. thank you :)
