### ISSUE TITLE
[Feat]: New display arrangement of widgets titles

### ISSUE THREAD

**Issue by MichalOren** [data-for-change/anyway-newsflash-infographics#959]
**Is your feature request related to a problem? Please describe.**
We currently concatenate the title and the subtitle in each infographic.
The main title describes the content / type of the infographic and the subtitle describes the location (section or street and city)

The required change is to stop the concatenate and divide title into 2 rows
The header will have the title ( bold ). 
On the second line, display the subtitle , containing location data

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/61007501/233662230-f4b6b58b-b2d7-4131-8df6-181b1908eb4c.png)

**Describe alternatives you've considered**
THIS CHANGE REFLECT ON ALL INFOGRAPHICS!!!
NEED TO GO OVER ETCH ONE AND VALIDATE THE DISPLAY 

**Additional context**

**Comment by shaked-hayek** [comment]
Already done
